version: '3.5'

services:
  mysql:
    image: mariadb:10.0.38
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpassword --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 1s
      retries: 5

  virutal-ldap:
    image: registry.cn-beijing.aliyuncs.com/ray-dockers/vldap:latest
    restart: always
    ports:
      - 1389:1389
    volumes:
      - ./config.js:/app/config.js
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - 'mysql'
